package com.mycompany.dobieracz001.frame;

import com.mycompany.dobieracz001.algorytm.AlgorytmEBM;
import static com.mycompany.dobieracz001.main.main.CAD;
import static com.mycompany.dobieracz001.main.main.EURO;
import static com.mycompany.dobieracz001.main.main.UPUST;
import com.mycompany.dobieracz001.wyniki.DACwynik;
import com.mycompany.dobieracz001.wyniki.EBMwynik;
import com.mycompany.dobieracz001.sql.sterownik.SqlSterownik;
import com.mycompany.dobieracz001.sql.sterownik.Sterownik;
import com.mycompany.dobieracz001.wyniki.BLCwynik;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 *
 * @since 2017-09-07, 15:45:17
 * @author Grzegorz Brodowski
 */
public class MainFrame extends javax.swing.JFrame {
    AlgorytmEBM sterownikiBLC;
    
    HashMap<String, Sterownik> dbSterowniki;
    SqlSterownik sql = new SqlSterownik();
    EBMwynik ebmwynik;
    BLCwynik blcwynik;
    String dac = "<html> "
                 + "sterownik: " + "<br> "
                 + "modul: " + "<br> "
                 + "modul: " + "<br> "
                 + "BLC: " + "<br> "
                 + "KAC: " + "<br> "
                 + "CYK: " + "<br> "
                 + "UI: " + "<br> "
                 + "DI: " + "<br> "
                 + "AO: " + "<br> "
                 + "DO: " + "<br> "
                 + "DIDO: " + "<br> "
                 + "cena: " + "<br> "
                 + "</html> ";

    ArrayList<DACwynik> dacwynik;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws ClassNotFoundException, SQLException {
        initComponents();
        jLabelDACnapis.setText(dac);
        jTextFieldCAD.setText(String.valueOf(CAD));
        jTextFieldEURO.setText(String.valueOf(EURO));
        jTextFieldUPUST.setText(String.valueOf(UPUST));
        jComboBoxPodTyp.setVisible(false);

    }
    

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAO = new javax.swing.JTextField();
        jTextFieldBO = new javax.swing.JTextField();
        jTextFieldBI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtoneBMGR = new javax.swing.JRadioButton();
        jTextFieldKAC = new javax.swing.JTextField();
        jTextFieldCYK = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButtoneBCON = new javax.swing.JRadioButton();
        jTextFieldBI_kac = new javax.swing.JTextField();
        jRadioButtonedBLC = new javax.swing.JRadioButton();
        jButtonWylicz = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldEURO = new javax.swing.JTextField();
        jTextFieldCAD = new javax.swing.JTextField();
        jTextFieldUPUST = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButtonWaluty = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxTyp = new javax.swing.JComboBox<>();
        jComboBoxPodTyp = new javax.swing.JComboBox<>();
        jButtonTabele = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelDACnapis = new javax.swing.JLabel();
        jLabelDAC1 = new javax.swing.JLabel();
        jLabelDAC2 = new javax.swing.JLabel();
        jLabelDAC3 = new javax.swing.JLabel();
        jLabelDAC4 = new javax.swing.JLabel();
        jLabelDAC5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTest = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelBLC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setPreferredSize(new java.awt.Dimension(1200, 650));
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sygnaly"));

        jLabel1.setText("UI");

        jTextFieldAO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAO.setText("0");
        jTextFieldAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAOActionPerformed(evt);
            }
        });

        jTextFieldBO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBO.setText("0");
        jTextFieldBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBOActionPerformed(evt);
            }
        });

        jTextFieldBI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBI.setText("0");
        jTextFieldBI.setSelectionStart(10);
        jTextFieldBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBIActionPerformed(evt);
            }
        });

        jLabel4.setText("AO");

        jTextFieldAI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAI.setText("0");
        jTextFieldAI.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldAI.setSelectionStart(10);
        jTextFieldAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAIActionPerformed(evt);
            }
        });

        jLabel2.setText("BI");

        jLabel3.setText("BO");

        jRadioButtoneBMGR.setText("eBMGR");
        jRadioButtoneBMGR.setToolTipText("");
        jRadioButtoneBMGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtoneBMGRActionPerformed(evt);
            }
        });

        jTextFieldKAC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldKAC.setText("0");
        jTextFieldKAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKACActionPerformed(evt);
            }
        });

        jTextFieldCYK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCYK.setText("0");
        jTextFieldCYK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCYKActionPerformed(evt);
            }
        });

        jLabel16.setText("KAC");

        jLabel17.setText("CYK");

        jRadioButtoneBCON.setText("eBCON");
        jRadioButtoneBCON.setToolTipText("");
        jRadioButtoneBCON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtoneBCONActionPerformed(evt);
            }
        });

        jTextFieldBI_kac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBI_kac.setText("0");
        jTextFieldBI_kac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBI_kacActionPerformed(evt);
            }
        });

        jRadioButtonedBLC.setText("BLC");
        jRadioButtonedBLC.setToolTipText("");
        jRadioButtonedBLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonedBLCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldKAC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCYK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBI_kac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtoneBCON)
                            .addComponent(jRadioButtoneBMGR)
                            .addComponent(jRadioButtonedBLC))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBI_kac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtoneBMGR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtoneBCON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonedBLC))
        );

        jButtonWylicz.setText("Wylicz");
        jButtonWylicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWyliczActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cena"));

        jTextFieldEURO.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldCAD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldUPUST.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel18.setText("EURO");

        jLabel19.setText("CAD");

        jLabel20.setText("UPUST");

        jButtonWaluty.setText("Waluty");
        jButtonWaluty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWalutyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEURO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCAD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUPUST, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonWaluty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEURO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUPUST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonWaluty))
        );

        jButtonClose.setText("Zamknij");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generowanie Tabel"));

        jComboBoxTyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "eBM", "DAC", "BLC", "" }));
        jComboBoxTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypActionPerformed(evt);
            }
        });

        jComboBoxPodTyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "wersja 1", "wersja 2", "wersja 3", "wersja 4", "wersja 5" }));
        jComboBoxPodTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPodTypActionPerformed(evt);
            }
        });

        jButtonTabele.setText("Tabele");
        jButtonTabele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTabele, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPodTyp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTyp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxPodTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTabele)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Wyliczenia"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("DAC"));

        jLabelDACnapis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDACnapis.setText("DAC");

        jLabelDAC1.setText("1");

        jLabelDAC2.setText("2");

        jLabelDAC3.setText("3");

        jLabelDAC4.setText("4");

        jLabelDAC5.setText("5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDACnapis)
                .addGap(18, 18, 18)
                .addComponent(jLabelDAC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDAC2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDAC3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDAC4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDAC5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDACnapis)
                    .addComponent(jLabelDAC1)
                    .addComponent(jLabelDAC2)
                    .addComponent(jLabelDAC3)
                    .addComponent(jLabelDAC4)
                    .addComponent(jLabelDAC5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("eBM"));

        jLabelTest.setText("WYLICZANIE_eBM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTest)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("BLC"));

        jLabelBLC.setText("WYLICZANIE_BLC");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBLC)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabelBLC)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonWylicz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClose))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonWylicz)
                            .addComponent(jButtonClose))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBIActionPerformed
        jTextFieldBI.select(0, jTextFieldAI.getSelectionEnd());
    }//GEN-LAST:event_jTextFieldBIActionPerformed

    private void jTextFieldAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAOActionPerformed
        jTextFieldAO.select(0, jTextFieldAI.getSelectionEnd());
    }//GEN-LAST:event_jTextFieldAOActionPerformed

    private void jTextFieldBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBOActionPerformed

    private void jButtonWyliczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWyliczActionPerformed
        wyliczanieModulow();
    }//GEN-LAST:event_jButtonWyliczActionPerformed

    private void jTextFieldKACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKACActionPerformed

    private void jTextFieldCYKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCYKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCYKActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonWalutyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWalutyActionPerformed
        EURO = Double.parseDouble(jTextFieldEURO.getText());
        CAD = Double.parseDouble(jTextFieldCAD.getText());
        UPUST = Double.parseDouble(jTextFieldUPUST.getText());
        wyliczanieModulow();
    }//GEN-LAST:event_jButtonWalutyActionPerformed

    private void jTextFieldBI_kacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBI_kacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBI_kacActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jRadioButtonedBLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonedBLCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonedBLCActionPerformed

    private void jButtonTabeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabeleActionPerformed

        if (jComboBoxTyp.getSelectedIndex() == 0) {
            TabeleFrame tb = new TabeleFrame(ebmwynik.wypiszTabele2());
            tb.setVisible(true);
        }
        if (!dacwynik.isEmpty()) {
            if (jComboBoxTyp.getSelectedIndex() == 1 & jComboBoxPodTyp.getSelectedIndex() == 0) {
                TabeleFrame tb = new TabeleFrame(dacwynik.get(0).wypiszTabele2());
                tb.setVisible(true);
            }

            if (jComboBoxTyp.getSelectedIndex() == 1 & jComboBoxPodTyp.getSelectedIndex() == 1) {
                TabeleFrame tb = new TabeleFrame(dacwynik.get(1).wypiszTabele2());
                tb.setVisible(true);
            }
            if (jComboBoxTyp.getSelectedIndex() == 1 & jComboBoxPodTyp.getSelectedIndex() == 2) {
                TabeleFrame tb = new TabeleFrame(dacwynik.get(2).wypiszTabele2());
                tb.setVisible(true);
            }
            if (jComboBoxTyp.getSelectedIndex() == 1 & jComboBoxPodTyp.getSelectedIndex() == 3) {
                TabeleFrame tb = new TabeleFrame(dacwynik.get(3).wypiszTabele2());
                tb.setVisible(true);
            }
            if (jComboBoxTyp.getSelectedIndex() == 1 & jComboBoxPodTyp.getSelectedIndex() == 4) {
                TabeleFrame tb = new TabeleFrame(dacwynik.get(4).wypiszTabele2());
                tb.setVisible(true);
            }

            if (jComboBoxTyp.getSelectedIndex() == 2) {
                TabeleFrame tb = new TabeleFrame(blcwynik.wypiszTabele2());
                tb.setVisible(true);
            }
        }

    }//GEN-LAST:event_jButtonTabeleActionPerformed

    private void jComboBoxTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypActionPerformed
        if (jComboBoxTyp.getSelectedIndex() == 1)
            jComboBoxPodTyp.setVisible(true);
        else
            jComboBoxPodTyp.setVisible(false);
    }//GEN-LAST:event_jComboBoxTypActionPerformed

    private void jComboBoxPodTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPodTypActionPerformed

    }//GEN-LAST:event_jComboBoxPodTypActionPerformed

    private void jRadioButtoneBMGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtoneBMGRActionPerformed
        if(jRadioButtoneBMGR.isSelected()) jRadioButtoneBCON.setSelected(false);
    }//GEN-LAST:event_jRadioButtoneBMGRActionPerformed

    private void jRadioButtoneBCONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtoneBCONActionPerformed
        if(jRadioButtoneBCON.isSelected()) jRadioButtoneBMGR.setSelected(false);
    }//GEN-LAST:event_jRadioButtoneBCONActionPerformed

    private void jTextFieldAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAIActionPerformed
        jTextFieldAI.selectAll();
        
    }//GEN-LAST:event_jTextFieldAIActionPerformed

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonTabele;
    private javax.swing.JButton jButtonWaluty;
    private javax.swing.JButton jButtonWylicz;
    private javax.swing.JComboBox<String> jComboBoxPodTyp;
    private javax.swing.JComboBox<String> jComboBoxTyp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBLC;
    private javax.swing.JLabel jLabelDAC1;
    private javax.swing.JLabel jLabelDAC2;
    private javax.swing.JLabel jLabelDAC3;
    private javax.swing.JLabel jLabelDAC4;
    private javax.swing.JLabel jLabelDAC5;
    private javax.swing.JLabel jLabelDACnapis;
    private javax.swing.JLabel jLabelTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtoneBCON;
    private javax.swing.JRadioButton jRadioButtoneBMGR;
    private javax.swing.JRadioButton jRadioButtonedBLC;
    private javax.swing.JTextField jTextFieldAI;
    private javax.swing.JTextField jTextFieldAO;
    private javax.swing.JTextField jTextFieldBI;
    private javax.swing.JTextField jTextFieldBI_kac;
    private javax.swing.JTextField jTextFieldBO;
    private javax.swing.JTextField jTextFieldCAD;
    private javax.swing.JTextField jTextFieldCYK;
    private javax.swing.JTextField jTextFieldEURO;
    private javax.swing.JTextField jTextFieldKAC;
    private javax.swing.JTextField jTextFieldUPUST;
    // End of variables declaration//GEN-END:variables

    public void wyliczanieModulow() {
        double AI = Double.valueOf(jTextFieldAI.getText());
        double BI = Double.valueOf(jTextFieldBI.getText());
        double AO = Double.valueOf(jTextFieldAO.getText());
        double BO = Double.valueOf(jTextFieldBO.getText());
        double KAC = Double.valueOf(jTextFieldKAC.getText());
        double CYK = Double.valueOf(jTextFieldCYK.getText());
        double BI_KAC = Double.valueOf(jTextFieldBI_kac.getText());
        KAC = BI_KAC / 3;
        boolean boolCYK = false;

        if (CYK > 0)
            boolCYK = true;

        boolean booleBMGR = jRadioButtoneBMGR.isSelected();
        boolean booleBCON = jRadioButtoneBCON.isSelected();

        try {
            dbSterowniki = sql.pobieranie();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (jRadioButtonedBLC.isSelected()) {
            sterownikiBLC = new AlgorytmEBM(AI, 0, AO, 0, boolCYK, booleBCON, booleBMGR, dbSterowniki, BI_KAC);
            ebmwynik = sterownikiBLC.CountEnteliIOs2();
            ebmwynik.addBLC(BI, BO);
            jLabelTest.setText(ebmwynik.wypisz());
        } else {
            sterownikiBLC = new AlgorytmEBM(AI, BI, AO, BO, boolCYK, booleBCON, booleBMGR, dbSterowniki, BI_KAC);
            ebmwynik = sterownikiBLC.CountEnteliIOs2();
            jLabelTest.setText(ebmwynik.wypisz());
        }
///////////////////////////////////////////////////////////////////////////////////
//DAC
///////////////////////////////////////////////////////////////////////////////////
        String dac = "<html> "
                     + "sterownik: " + "<br> "
                     + "modul: " + "<br> "
                     + "modul: " + "<br> "
                     + "KAC: " + "<br> "
                     + "CYK: " + "<br> "
                     + "UI: " + "<br> "
                     + "DI: " + "<br> "
                     + "AO: " + "<br> "
                     + "DO: " + "<br> "
                     + "cena: " + "<br> "
                     + "</html> ";
        String alfa = "";
        if (!jRadioButtonedBLC.isSelected())
            alfa = "select*from tabeladac where (l_UI+l_DI)>" + (BI + BI_KAC - 1)
                   + "AND (l_UI+l_DI)>" + (AI + BI + BI_KAC - 1)
                   + "AND l_UI>" + (AI - 1)
                   + "AND l_AO>" + (AO - 1)
                   + "AND l_DO>" + (BO - 1)
                   + "AND kac<" + (KAC + 1)
                   + "AND cyk<" + (CYK + 1);
        else
            alfa = "select*from tabeladac where "
                   + " l_UI>" + (AI - 1)
                   + "AND l_AO>" + (AO - 1)
                   + "AND kac<" + (KAC + 1)
                   + "AND cyk<" + (CYK + 1);
        try {
            dacwynik = sql.pobieranieDAC(alfa);
            if (!dacwynik.isEmpty())
                for (DACwynik d : dacwynik) {
                    if (jRadioButtonedBLC.isSelected())
                        d.addBLC(dbSterowniki.get("BLC-24A"), AI, BI, AO, BO);
                    d.wyliczNieuzywaneSygnaly(AI, BI, AO, BO);
                }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        Collections.sort(dacwynik, new Comparator<DACwynik>() {
                     public int compare(DACwynik o1, DACwynik o2) {
                         if (o1.getCena() == o2.getCena())
                             return 0;
                         return o1.getCena() < o2.getCena() ? -1 : 1;
                     }
                 });

        jLabelDAC1.setText("brak");
        jLabelDAC2.setText("brak");
        jLabelDAC3.setText("brak");
        jLabelDAC4.setText("brak");
        jLabelDAC5.setText("brak");

        if (!dacwynik.isEmpty()) {
            jLabelDAC1.setText(dacwynik.get(0).wypisz2());
            if (dacwynik.size() > 1)
                jLabelDAC2.setText(dacwynik.get(1).wypisz2());
            if (dacwynik.size() > 2)
                jLabelDAC3.setText(dacwynik.get(2).wypisz2());
            if (dacwynik.size() > 3)
                jLabelDAC4.setText(dacwynik.get(3).wypisz2());
            if (dacwynik.size() > 4)
                jLabelDAC5.setText(dacwynik.get(4).wypisz2());
        }
///////////////////////////////////////////////////////////////////////////////////
//BLC
///////////////////////////////////////////////////////////////////////////////////
        jLabelBLC.setText("brak");
        if (AI < 5 & AO == 0) {
            blcwynik = new BLCwynik(dbSterowniki, BI + BI_KAC, BO, AI);
            jLabelBLC.setText(blcwynik.wypisz());
        }

    }//koniec wyliczanie modulow
    
    

}
